{
    "questionRequestList":
     [
        {"answerRequestList":[{"questionAnswer":"本科","questionOptionId":2579}],"surveyQuestionId":1125},
        {"answerRequestList":[{"questionAnswer":"消防类专业","questionOptionId":2587}],"surveyQuestionId":1127},
        {"answerRequestList":[{"questionAnswer":"4年及以上","questionOptionId":3015}],"surveyQuestionId":1129},
        {"answerRequestList":[{"questionAnswer":"3年及以上","questionOptionId":3043}],"surveyQuestionId":1131},
        {"answerRequestList":[{"questionAnswer":"河北省"}],"surveyQuestionId":1133},
        {"answerRequestList":[{"questionAnswer":"4"}],"surveyQuestionId":1135}
     ],
    "surveyId":165,
    "terminal":4
}